# Generated by Django 5.2 on 2025-05-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0002_techstack_alter_profileinfo_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ProjectName", models.CharField(max_length=255)),
                ("thumbnail", models.ImageField(null=True, upload_to="")),
                ("url", models.CharField(max_length=255)),
            ],
        ),
    ]
