# Generated by Django 5.2 on 2025-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Institution", models.CharField(max_length=255)),
                ("Role", models.CharField(max_length=255)),
            ],
        ),
    ]
