# Generated by Django 5.2 on 2025-05-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ceritifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
