# Generated by Django 5.2 on 2025-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_ceritifications_file_alter_profileinfo_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.FileField(upload_to="resune")),
            ],
        ),
    ]
